const KITCHENS = [
  {
    id: "k1",
    name: "Marlow & Sons Kitchen",
    neighborhood: "Williamsburg",
    city: "Brooklyn, NY",
    address: "81 Broadway, Brooklyn, NY 11249",
    rate: 42,
    rating: 4.9,
    reviews: 38,
    hours: "10:00 PM – 6:00 AM",
    capacity: 4,
    equipment: ["6-burner range", "Convection oven", "Walk-in cooler", "Prep tables", "Dish pit"],
    permits: "NYC DOHMH Food Service Establishment",
    host: "Andrew T.",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80",
    blurb: "Restaurant kitchen idle after last seating. Full line, walk-in, and street-level loading.",
    rules: "Clean as you go. No deep fryer after 4am. Host approves first booking.",
    availableNights: [0, 1, 2, 3, 4, 5, 6]
  },
  {
    id: "k2",
    name: "Clinton Hill Commissary",
    neighborhood: "Clinton Hill",
    city: "Brooklyn, NY",
    address: "412 Myrtle Ave, Brooklyn, NY 11205",
    rate: 28,
    rating: 4.7,
    reviews: 61,
    hours: "9:00 PM – 7:00 AM",
    capacity: 6,
    equipment: ["Double convection", "Hobart mixer", "Proofing cabinet", "3-compartment sink", "Dry storage"],
    permits: "NYC DOHMH + NYS Ag & Markets",
    host: "Priya S.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=600&q=80",
    blurb: "Bakery-friendly suite. Overnight bakers and farmers-market vendors welcome.",
    rules: "Label everything. Allergen protocol posted. Card on file required.",
    availableNights: [0, 1, 2, 3, 4, 6]
  },
  {
    id: "k3",
    name: "Astoria Grill After Dark",
    neighborhood: "Astoria",
    city: "Queens, NY",
    address: "28-14 31st St, Astoria, NY 11102",
    rate: 32,
    rating: 4.8,
    reviews: 24,
    hours: "11:00 PM – 6:00 AM",
    capacity: 3,
    equipment: ["Flat top", "Chargrill", "Reach-in fridge", "Prep sink", "Loading alley"],
    permits: "NYC DOHMH Food Service Establishment",
    host: "Nikos P.",
    image: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80",
    blurb: "Greek restaurant line available after close. Ideal for catering runs and meal-prep.",
    rules: "No pork on shared boards. Host must approve first three bookings.",
    availableNights: [0, 1, 2, 3, 4]
  },
  {
    id: "k4",
    name: "Harlem Oven Collective",
    neighborhood: "Harlem",
    city: "Manhattan, NY",
    address: "214 W 125th St, New York, NY 10027",
    rate: 48,
    rating: 5.0,
    reviews: 19,
    hours: "10:30 PM – 5:30 AM",
    capacity: 5,
    equipment: ["Deck oven", "Combi oven", "Blast chiller", "Walk-in freezer", "Packaging station"],
    permits: "NYC DOHMH + fire suppression current",
    host: "Denise R.",
    image: "https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80",
    blurb: "Production kitchen with packaging space. Pop-ups and packaged goods.",
    rules: "Liability COI required after first booking. Quiet loading after midnight.",
    availableNights: [1, 2, 3, 4, 5, 6]
  },
  {
    id: "k5",
    name: "Red Hook Fish House",
    neighborhood: "Red Hook",
    city: "Brooklyn, NY",
    address: "391 Van Brunt St, Brooklyn, NY 11231",
    rate: 36,
    rating: 4.6,
    reviews: 15,
    hours: "9:30 PM – 6:00 AM",
    capacity: 4,
    equipment: ["Ice machine", "Seafood sink", "Range", "Convection", "Walk-in"],
    permits: "NYC DOHMH",
    host: "Luis M.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=80",
    blurb: "Waterfront kitchen with raw bar sinks. Caterers and food trucks.",
    rules: "Seafood waste in designated bins only.",
    availableNights: [0, 2, 3, 4, 5]
  },
  {
    id: "k6",
    name: "Park Slope Sunday Kitchen",
    neighborhood: "Park Slope",
    city: "Brooklyn, NY",
    address: "218 7th Ave, Brooklyn, NY 11215",
    rate: 38,
    rating: 4.8,
    reviews: 44,
    hours: "10:00 PM – 7:00 AM",
    capacity: 3,
    equipment: ["Range", "Pizza deck", "Mixer", "Reach-ins", "Dish machine"],
    permits: "NYC DOHMH",
    host: "Claire B.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80",
    blurb: "Neighborhood restaurant line. Cookie vendors and small caterers love the overnight window.",
    rules: "Must vacate by 7am sharp before brunch prep.",
    availableNights: [0, 1, 2, 3, 6]
  }
];

const PLATFORM_FEE = 0.10;
const SLOT_START = 22;
const DEFAULT_SLOTS = [
  { start: "22:00", end: "01:00", hours: 3 },
  { start: "01:00", end: "04:00", hours: 3 },
  { start: "04:00", end: "07:00", hours: 3 }
];
